#!/usr/bin/env python3
# Copyright (c) 2026 Bruce Blay
# SPDX-License-Identifier: GPL-3.0-or-later
"""Convert a directory of mono 16-bit PCM WAVs into src/Samples.h.

Each file must be named <instrument>_<root midi>.wav, mono 16-bit PCM at
32000 Hz, matching chime::rate. The root in the filename is the pitch the
clip was recorded or rendered at; the player resamples from there to reach
every other note, so getting it wrong detunes the whole zone.

This tool does not resample or downmix. Sources and their licenses belong in
docs/SOURCES.md before anything recorded is embedded here.
"""
import argparse
import struct
import wave
from collections import defaultdict
from pathlib import Path

RATE = 32000


def read_pcm16_mono(path: Path):
    with wave.open(str(path), 'rb') as w:
        if w.getsampwidth() != 2:
            raise SystemExit(f'{path}: expected 16-bit PCM, got {w.getsampwidth() * 8}-bit')
        if w.getnchannels() != 1:
            raise SystemExit(f'{path}: expected mono, got {w.getnchannels()} channels')
        if w.getframerate() != RATE:
            raise SystemExit(f'{path}: expected {RATE} Hz, got {w.getframerate()} Hz')
        frames = w.readframes(w.getnframes())
    return struct.unpack(f'<{len(frames) // 2}h', frames)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory', type=Path)
    parser.add_argument('--out', type=Path, default=Path(__file__).resolve().parents[1] / 'src/Samples.h')
    args = parser.parse_args()

    instruments = defaultdict(list)
    for path in sorted(args.directory.glob('*.wav')):
        name, _, root = path.stem.rpartition('_')
        if not name or not root.isdigit():
            raise SystemExit(f'{path}: expected <instrument>_<root midi>.wav')
        instruments[name].append((int(root), path))

    if not instruments:
        raise SystemExit(f'{args.directory}: no .wav files found')

    lines = ['// Copyright (c) 2026 Bruce Blay',
             '// SPDX-License-Identifier: GPL-3.0-or-later',
             '#pragma once',
             '#include <cstdint>',
             '',
             '#ifndef PROGMEM',
             '#define PROGMEM',
             '#endif',
             '',
             '// Generated by tools/embed_samples.py -- do not hand-edit.',
             '//',
             '// Multisampled tuned percussion, one zone every few semitones. The clips',
             '// live in flash and are read from there a sample at a time; nothing here',
             '// is copied into RAM.',
             'namespace samples {',
             '']
    total = 0
    for name, entries in sorted(instruments.items()):
        for root, path in sorted(entries):
            data = read_pcm16_mono(path)
            total += len(data) * 2
            lines.append(f'static const int16_t {name}_{root}[{len(data)}] PROGMEM = {{')
            for i in range(0, len(data), 50):
                lines.append(','.join(str(v) for v in data[i:i + 50]) + ',')
            lines.append('};')
            lines.append('')

    lines.append('struct Zone { const int16_t* data; uint32_t length; uint8_t root; };')
    lines.append('// low and high are the register the score should play this instrument in:')
    lines.append('// its own recorded range, give or take a couple of semitones, rather than')
    lines.append('// one register borrowed from the synth for all of them.')
    lines.append('struct Instrument { const Zone* zones; uint8_t count; uint8_t low, high; };')
    lines.append('')
    for name, entries in sorted(instruments.items()):
        lines.append(f'static const Zone {name}_zones[] = {{')
        for root, path in sorted(entries):
            data_len = len(read_pcm16_mono(path))
            lines.append(f'  {{{name}_{root}, {data_len}, {root}}},')
        lines.append('};')
    lines.append('')
    lines.append('static const Instrument instruments[] = {')
    for name, entries in sorted(instruments.items()):
        roots = sorted(root for root, _ in entries)
        low, high = max(0, roots[0] - 2), min(127, roots[-1] + 2)
        lines.append(f'  {{{name}_zones, {len(entries)}, {low}, {high}}},  // {name}, MIDI {low}-{high}')
    lines.append('};')
    lines.append(f'static constexpr unsigned instrumentCount = {len(instruments)};')
    lines.append('}')
    lines.append('')

    args.out.write_text('\n'.join(lines))
    print(f'{args.out}: {len(instruments)} instrument(s), {total / 1024:.0f} KB of samples')


if __name__ == '__main__':
    main()
